// Cloudflare Worker - Serves Vantage Flex static files
import { getAssetFromKV } from '@cloudflare/kv-asset-handler'

// Asset manifest will be generated by wrangler
const ASSET_MANIFEST = {}

addEventListener('fetch', event => {
  event.respondWith(handleRequest(event))
})

async function handleRequest(event) {
  const url = new URL(event.request.url)
  
  try {
    // Try to serve static assets
    const response = await getAssetFromKV(event, {
      ASSET_NAMESPACE: ASSET_MANIFEST,
      mapRequestToAsset: req => {
        // Serve index.html for root path
        const url = new URL(req.url)
        if (url.pathname === '/') {
          url.pathname = '/index.html'
        }
        return new Request(url.toString(), req)
      }
    })
    
    // Add security headers
    const headers = new Headers(response.headers)
    headers.set('X-Frame-Options', 'DENY')
    headers.set('X-Content-Type-Options', 'nosniff')
    headers.set('Referrer-Policy', 'strict-origin-when-cross-origin')
    
    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers
    })
  } catch (e) {
    // Return 404 page if asset not found
    if (e.status === 404) {
      return new Response(`
        <!DOCTYPE html>
        <html>
        <head><title>404 - Vantage Flex</title></head>
        <body style="background:#0a0a0f;color:#fff;font-family:sans-serif;text-align:center;padding:50px;">
          <h1>404 - Page Not Found</h1>
          <p>Go back to <a href="/" style="color:#ff6b35;">home</a></p>
        </body>
        </html>
      `, { 
        status: 404, 
        headers: { 'Content-Type': 'text/html' } 
      })
    }
    
    return new Response(`Error: ${e.message}`, { status: 500 })
  }
}
